# Generated by Django 4.2.5 on 2023-10-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('price', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('status_registration', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='OrderSendUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infos.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infos.users')),
            ],
        ),
        migrations.CreateModel(
            name='BaskedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_product', models.IntegerField()),
                ('total', models.BigIntegerField()),
                ('basked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basked_set', to='infos.basked')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infos.product')),
            ],
        ),
        migrations.AddField(
            model_name='basked',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.users'),
        ),
    ]
